### ISSUE TITLE
Feature request: use UTF-8 as default encoding

### ISSUE THREAD

**Issue by basisbit** [SarutaSan72/Yass#124]
In the past few years, there has been a push to get rid of non-UTF-8 encodings from UltraStar txt files, in hope to reduce issues that people repeatedly have with special characters and localization.

Yass already fully supports UTF-8 and also has an option to set UTF-8 as the users default encoding.
However, it seems like this is not the default encoding after doing a fresh install, as reported here: https://github.com/UltraStar-Deluxe/Play/issues/376#issuecomment-1402739497

Thus, I'd like to kindly request if maybe the default encoding could be changed to UTF-8 in future Yass versions? Thanks in advance!

**Comment by SarutaSan72** [comment]
planned for next release; have to double-check that this does not corrupt files unintentionally when executing batch correction in song library

**Comment by SarutaSan72** [comment]
Your change simply toggles the flag to always safe in UTF8. 

Is this safe? I have only partly understood the process. In this W3C text I read that it is not safe. https://www.w3.org/International/articles/unicode-migration/

> Note that simply changing the character encoding of your pages to Unicode will not eliminate all character encoding problems. In fact, during the migration there is a significantly increased risk of such bugs, because existing data must be converted to Unicode, and the current encoding is not always known.

I am using the Mozilla detector, which is not reliable.

> character encoding detection is not a reliable process. Thus, you should keep the original bytes around

Now when I batch-process my library, every text file is written. Can you  proof that the conversion does not corrupt data in that case? 

Maybe someone else has a better understanding, or has actually tried and verified it. Currently I can't assess the risk.

**Comment by DoubleDee73** [comment]
If you manually check that checkbox and start batch-processing your library, it would have the same effect, wouldn't it?
From the feature request, I understood, that the issue was, that after a fresh install, that this wasn't the default behaviour.

I did check this by arbitarily changing the encoding to ANSI for some files in Notepad++ and editing and saving them in Yass for German, Italian and French with no problem (obviously with äöüàéú etc).
I did try converting GB2312 (Chinese), but that file wouldn't even display correctly from the get go.

In the end, it's as safe as it gets. As far as I understand, the universal detector is not reliable because if you have a txt that doesn't contain any bytes that clearly identify it as UTF-8, you can only detect the charset by the usage of an agglomaration of certain characters that identify the charset. There needs to be a certain trust, that people who have downloaded the txts did receive them in either ANSI or UTF8. I think, if you need Cyrillic, Hebrew, Chinese or whathaveyounot, you'd always opt for the latter, just to be on the safe side.

I did not understand the feature request to rewrite the universal charset detector... 
Maybe displaying a one-time Message-Box with a warning hint to backup their txts will do?

**Comment by SarutaSan72** [comment]
I can live with manually correcting UTF8 during song making, but not with destroying someone's song collection. 

For now, I have asked the US Asian community for input. I'll wait for a definite YES or NO from someone who actually uses this setting. With files having unknown encoding, or non-UTF8 files, or files that can be sung but have incorrect encodings - e.g. a UTF BOM that actually is BIG5, such things happen. 

I myself can't tell if I can make another release this year.

**Comment by DoubleDee73** [comment]
Okay, fair enough. I don't need this feature anyway, because all my files are in UTF8 anyway.
Have you ever had feedback that people with non-latin writing ever used Yass without UTF8? Like I said, I wasn't able to open a file in GB2312 in Chinese, so I would not be surprised, if other non-ANSI, non-UTF charsets wouldn't open properly either.

**Comment by basisbit** [comment]
Imho it would be good to somehow get rid of non-UTF8 file encoding for ultrastar files, because of all the problems that happen with non-UTF8 encoded files when being opened in the various tools/games. Thus I asked in this here feature request to have UTF-8 as default encoding, I didn't ask to brute-force convert all other files without even asking the user. Just by default saving new or lyrics-edited files as UTF-8 would imho already be a big improvement.

**Comment by basisbit** [comment]
The reason for why I try to push for more UTF-8 is that non-utf8 files cause severe issues and are like a third of reported issues of the karaoke games.

**Comment by SarutaSan72** [comment]
> Just by default saving new or lyrics-edited files as UTF-8 would imho already be a big improvement.

True, this should be done. --> I'll find a way without changing the default encoding, which would affect also older files.
--> assign me

**Comment by SarutaSan72** [comment]
Done in v2.5.0. Yass now uses UTF-8 for changing saves in the song editor and for creating new files (library > file > new...).

For compatibility, the encoding is not changed by batch-correcting multiple files (library > errors > multiselect/all > correct).

Thanks for your patience.

**Comment by basisbit** [comment]
Thank you very much! 🥳
