### ISSUE TITLE
4k resolution support

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#13]
(I don't have a 4k screen, so I can't tell by myself) but other users seems to have problems with the text in resolution ultra-high.

[link removed]

**Comment by SarutaSan72** [comment]
Uh, yes. Other users reported this, too. I refered to https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display/1207925#1207925

I will check if there's a way solving this application-side.

**Comment by SarutaSan72** [comment]
I have checked both OracleJDK and OpenJDK bug databases and the problem seems fixed in Java 9. Both were released in Sep 2017. I have never ever used OpenJDK.

Could someone with a 4K screen test this with Oracle Java 9? Make sure that not an older Java version is used.

**Comment by SarutaSan72** [comment]
This can be tested now. Steps:
- Someone with a 4K monitor (I don't have one)
- Install **JRE 9** from http://www.oracle.com/technetwork/java/javase/downloads
- Open Command Shell (windows: `cmd.exe`)
- Check that Java 9 is used: `java --version` should print something like: 
> java 9.0.4
> Java(TM) SE Runtime Environment (build 9.0.4+11)
> Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
- Start Yass:  `java -jar yass-1.9.0.jar`
- Check if 4k resolution problems are solved
-- Window size okay?
-- Font size okay?
-- Icon size okay? (they will look blurred since they are zoomed)

**Comment by Daniel20Ultrastar-es** [comment]
talking with team mate who has 4k monitor:

- the size of the window is ok
- the font size is ok, but everything looks blurred.
- icon size is ok.

**Comment by SarutaSan72** [comment]
At least the most basic stuff works now. Font size can be set in the preferences, eventually that fixes the blurred text. But it seems they zoom the output instead of the font size. Maybe a flag is missing? I fear I cannot debug this without a 4k monitor.

I close this issue and move the blurred text issue to a new issue. Thanks for testing!
