### ISSUE TITLE
bad sync

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#8]
yass moves 1 square (one beat) the whole song to the right respect to that BPM.

Once, a song is finished, you can check in ultrastar editor (pressing 'e' key at "select song" screen) the whole song is moved one beat to the right. Pressing 'p' key you can hear the "tick" sound doesn't fit at all.

I've checked the code in ultrastar, but it seems a yass issue. Could you check it?

(sorry, for not signs of life, we'll try to help you after the release of our version this year) ;)

**Comment by SarutaSan72** [comment]
Hi there, I'll check this. As you see, I can spare a little time here :-)

**Comment by SarutaSan72** [comment]
Yes, I can reproduce that shift, too. I tried debugging, but the waveform display seems broken in Yass. 

Can USDX version show the waveform together with the notes? 
I see the waveform on top-right, and would like to see which part belongs to the current note.
(Either by painting the waveform over the shown notes, or the current note into the waveform.)

**Comment by Daniel20Ultrastar-es** [comment]
I think so, but I can't tell. You can check it in their repo: https://github.com/UltraStar-Deluxe/USDX/blob/master/src/screens/UScreenEditSub.pas

We've delete the editor in our version worldparty to improve the performance in the game. We prefer use your app to edit a song. Implement an internal editor in the game is hard to develop, and the results are an extremmelly poor experience and buggy. (most part are broken too)

**Comment by SarutaSan72** [comment]
Okay, I've fixed the waveform bug. And finetuned the Yass Accuracy Test four times:
- USDX with bit reservoir (explained here: http://yass-along.com/about-accuracy/)
- YASS with bit reservoir
- USDX with bit reservoir disabled
- YASS with bit reservoir disabled

Result: [yass_usdx_accuracy.zip](https://github.com/SarutaSan72/Yass/files/1700318/yass_usdx_accuracy.zip)

![bitres](https://user-images.githubusercontent.com/27969336/35876566-f1129bda-0b72-11e8-89f8-64e4d01f7998.png)
USDX (blue outline) and YASS (red) - bit reservoir
In line 6, USDX is 100ms before YASS

![bitresdis](https://user-images.githubusercontent.com/27969336/35876631-23d86fe0-0b73-11e8-9cb8-4f56757c4e80.png)
USDX (blue outline) and YASS (red) - bit reservoir disabled
In line 6, USDX is 150ms before YASS

YASS seems to match the waveform pretty well, while USDX starts too early. Since I coded the waveforms myself, I cannot be sure. Therefore I asked if USDX can show waveforms and notes together in a single timeline.

When playing these songs in USDX, I prefer the YASS versions. Again this might be subjective.
Please check yourself. I am using Lyrics effect "zoom", it is more effective than the default one.

**Comment by SarutaSan72** [comment]
So in short, we need someone who judges the above results (yass_usdx_accuracy.zip) in USDX player. 
- "Sing" YASS and USDX with bit reservoir disabled -> which is better?
- "Sing" ASS/USDX with bit reservoir -> which is better?

Then  someone should verify manually that the beats match the tones in the MP3 file. 
- Read the in/out-milliseconds of the tones in e.g. Audacity (use the MP3 with bit reservoir disabled)
- From the YASS/USDX txt file, calculate the beats' milliseconds 
- Which matches better? (Yass can position on full frames only, here each frame is 26ms)

**Comment by Daniel20Ultrastar-es** [comment]
I don't see difference in ultrastar, with & without bit reservoir, but yes with yass / ultrastar.

if you tap the notes of yass file in ultrastar, you can hear the noise sound in the silence note, not in the correct one. Notes in ultrastar files sounds ok in the game. 

Is it possible to add a in yass a shift option, with the issue fixed by default, giving the option to change?

**Comment by SarutaSan72** [comment]
And notes in yass files, how do they sound in the game? Better or worse than the ultrastar files?

I can add that shift option, but it might be better to fix the shift in USDX editor, if that's causing the problem. Is this shift really constant or is it increasing line by line. I still believe the shift stems from seeking positions, and appears only in the editors. In 2010 there hasn't been such a noticable shift, and I haven't changed playback since then. As far as I remember.

**Comment by Daniel20Ultrastar-es** [comment]
is not only in the editor affects to the game engine too.

the shift is constant. it doesn't increase line by line. The test you can do is after create a song. select all notes in yass (edit -> select all) and then moves 1 beat to the left (shift + left arrow) and save. If you compare in the editor of ultrastar, once you moved that beat, sounds ok, but yass files with no resync sounds bad.

with your test, if you open any of the yass txt in the editor ultrastar and go to the last line, if you press space key through the notes, you'll hear the sound in the silence notes as I said before. but in the other ultrastar files works fine.

Obviously, when you move 1 beat the whole song in yass, the app will mark the rythm in the next tone, which makes yass impossible to use.

idk, maybe a button to enable / disable this shift would be ok, or just correct this shift.

**Comment by SarutaSan72** [comment]
I understand that the editors show the shift and that it is better to produce the same results.
My question is: which editor should be adapted? 

If you're sure the text files edited with USDX are better, then I will include that option.
Else I would fork the USDX editor and try to convince developers there.

Are you really sure? Don't look at the USDX editor, just play the game and judge.
Use the lyrics effect "zoom", note starts can be seen better with that.

**Comment by SarutaSan72** [comment]
Okay, I have added an option to set seek-in/out offsets in milliseconds.
These are added when seeking a position in the MP3 file.
Download is available as pre-release.

I don't favor beat offsets, because they depend on the actual BPM.

You can play with these values to simulate the USDX editor. 
For the Yass Accuracy Test (bit reservoir disabled) the values 100/150 seem to fit.
If they prove to match *all* finetuned MP3s in USDX, I can add a preset for USDX.
You might want to test that on different systems.

Would this help you?

**Comment by Daniel20Ultrastar-es** [comment]
Let me do more testing, I'll answer you before this week ends.

**Comment by SarutaSan72** [comment]
Are you contributing to usdx, too? My holiday is over, you can take your time. I hope you find a bug there :crossed_fingers:

**Comment by Daniel20Ultrastar-es** [comment]
nope. I work for Ultrastar España team, we develop the "Ultrastar Deluxe WorldParty" (it's a fork of the old usdx 1.1). I don't work with them because a LONG story... (the new usdx is using most of our new features) so now we have different paths...

Thanks for these days of updates, we're really focus in the next release of our project, and we don't have the time we wish to help other projects (but we'll do it)

The bug hunting has began!!

**Comment by SarutaSan72** [comment]
yep :grin:

**Comment by Daniel20Ultrastar-es** [comment]
Done, this is already fixed by us in Ultrastar, so the new feature is not necessary. You can close this issue.

**Comment by SarutaSan72** [comment]
Nice! Good work
