### ISSUE TITLE
Add Maven support

### ISSUE THREAD

**Issue by TeLiXj** [SarutaSan72/Yass#87]
The project could use Maven to manage dependencies like any modern software.
I'm trying to add a new one that have many other dependencies and it's terrible, because I have to add all of them manually.

**Comment by DoubleDee73** [comment]
Question is, if I should have migrated to Gradle at this point...

**Comment by TeLiXj** [comment]
I'm not an expert on this tools. Gradle is better than Maven for a project like this?

**Comment by DoubleDee73** [comment]
Maven has been around longer than Gradle. The latter is also widely used and builds faster than Maven. Both options are a huge step up to how dependencies are handled. It depends on what all contributors feel more comfortable with.
Personally, I'd go with Gradle, because I know it from work. I'm fine with Maven, too...

**Comment by TeLiXj** [comment]
I don't have any preference, I only need a system to manage dependencies. If you prefer Gradle it's fine for me, unless that @SarutaSan72 have some to say

**Comment by SarutaSan72** [comment]
Won't be done, at least not by me. Please refer to #136 and DoubleDee73's fork.

Since this issue is of 2021, I'll close it as outdated.
